name: Vue app CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  test-build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x]

    steps:
    - uses: actions/checkout@v3
    - name: vue test buid
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: NODE_OPTIONS=--openssl-legacy-provider npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: test-build

    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: |
          cd /var/www/dnd-vue
          git pull origin main
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          export NODE_OPTIONS=--openssl-legacy-provider
          npm ci
          pm2 restart dnd-vue